### ISSUE TITLE
Relies on deprecated syntex crate

### ISSUE THREAD

**Issue by stouset** [gnzlbg/ctest#77]
Syntex is deprecated and unmaintained and has been so for two years. Can we find an alternative?

**Comment by gnzlbg** [comment]
> Can we find an alternative?

I don't know of any. The syntex crate was deprecated without providing a replacement. We maintain our own fork of `syntex` (syntex2) for that.

**Comment by gnzlbg** [comment]
This is a duplicate of #70 .
