### ISSUE TITLE
typedef for a struct is missing the struct keyword

### ISSUE THREAD

**Issue by elichai** [gnzlbg/ctest#88]
Him
if you have rust code like:
```
type flock64 = flock;
struct flock {...}
```

The C code will use `flock64` instead of `struct flock64`.
Is that something I should handle with `type_name` myself?

CC https://github.com/rust-lang/libc/pull/1561

**Comment by gnzlbg** [comment]
This is working as intended. In Rust, `flock64` is a type alias, not a `struct`, and that's how it gets expanded to C. If you want it to expand to a `struct`, either define a Rust struct, or use `type_name` to configure the behavior.
